name: ZIVPN Native Build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  BuildAPK:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build APK (Release)
        run: |
          chmod +x gradlew
          ./gradlew :app:assembleAlphaRelease

      - name: Upload ZIVPN Native APK
        uses: actions/upload-artifact@v4
        with:
          name: ZIVPN-Native-APK
          path: app/build/outputs/apk/alpha/release/*.apk
